apiVersion: v1
kind: Service
metadata:
  name: webmicroservicestarter-service
spec:
  ports:
  - port: 80
    targetPort: 8080 # Port in microservice
    protocol: TCP
    name: http
  selector:
    app: webmicroservicestarter